import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <footer className="right-0 p-4 bg-white shadow-md">
        <div className="container flex items-center justify-center mx-auto">
          <a
            href="https://github.com/znichola/codenames-grid-gen"
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center gap-2 text-gray-700 hover:text-indigo-600 transition-colors"
          >
            {/* <Github size={20} /> */}
            <span>View source on GitHub</span>
            
          </a>
        </div>
      </footer>
      </body>
    </html>
  );
}
